name: Prune Codecov .coveragerc
on: [push]

env:
  DEFAULT_PYTHON: "3.12.2"
  BRANCH_NAME: "prune_coveragerc"
  # @todo My details, just for testing - Later change to bot user id?
  USER_EMAIL: "17680170+davet2001@users.noreply.github.com"
  USER_NAME: "Dave T"
jobs:


  base:
    uses: ./.github/workflows/ci.yml  
  
  prune-coveragerc-check:
    runs-on: ubuntu-22.04
    needs: [base]
    outputs:
      changes: ${{ steps.detect.outputs.changes }}
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v4.1.2
      - name: Set up Python ${{ needs.base.outputs.default-python-version  }}
        id: python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: "3.12"
          check-latest: true
      - name: Restore full Python ${{ env.DEFAULT_PYTHON }} virtual environment
        id: cache-venv
        uses: actions/cache/restore@v4.0.2
        with:
          path: venv
          fail-on-cache-miss: true
          key: ${{ runner.os }}-${{ env.DEFAULT_PYTHON }}-${{ needs.base.outputs.python_cache_key }}
      - name: Run pytest followed by coveragerc prune
        run: |
          . venv/bin/activate
          python3 -m script.check_coveragerc
      - name: Detect if anything was pruned
        id: detect
        run: |
          change_count=$(git diff --numstat | wc -l)
          echo "$change_count files changed"
          echo "changes=$change_count" >> $GITHUB_OUTPUT

  prune-coveragerc-commit:
    runs-on: ubuntu-22.04
    needs: [prune-coveragerc-check]

    if: needs.prune-coveragerc-check.outputs.changes
    steps: 
      - name: Create branch and add ${{ needs.prune-coveragerc-check.outputs.changes }} files
        run: |
          ls -la
          git checkout -b ${{ env.BRANCH_NAME }}
          git config --local user.email ${{ env.USER_EMAIL }}
          git config --local user.name ${{ env.USER_NAME }}
          git add .coveragerc
          git commit -m "Remove unnecessary .coveragerc entries"
          git push
      #- name: Create pull request
        # run: |
        #   gh 

